In [1]:
import numpy as np
from keras.utils import to_categorical
from keras import models
from keras import layers
from keras.datasets import mnist
import matplotlib.pyplot as plt

C:\Users\Shahzad Ahsan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images.shape


(60000, 28, 28)

In [3]:
 len(train_labels)


60000

In [4]:
 test_images.shape

(10000, 28, 28)

In [5]:
len(test_labels)

10000

In [6]:
 test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [7]:
network = models.Sequential()
network.add(layers.Dense(591, activation='relu', input_shape=(28 * 28,)))

network.add(layers.Dense(10, activation='softmax'))
#first layer always contain two layers.
#relu converts relarity into non-relarity
#softmax ,return probablity of every class.(show all output)

In [8]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [9]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [10]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [11]:
network.fit(train_images, train_labels, epochs=9, batch_size=128)

Epoch 1/9
60000/60000 [==============================] - 7s 120us/step - loss: 0.2498 - acc: 0.9275
Epoch 2/9
60000/60000 [==============================] - 7s 111us/step - loss: 0.1008 - acc: 0.9703
Epoch 3/9
60000/60000 [==============================] - 7s 114us/step - loss: 0.0657 - acc: 0.9806
Epoch 4/9
60000/60000 [==============================] - 7s 113us/step - loss: 0.0477 - acc: 0.9862
Epoch 5/9
60000/60000 [==============================] - 7s 115us/step - loss: 0.0348 - acc: 0.9894
Epoch 6/9
60000/60000 [==============================] - 7s 115us/step - loss: 0.0268 - acc: 0.9919
Epoch 7/9
60000/60000 [==============================] - 7s 112us/step - loss: 0.0210 - acc: 0.9935
Epoch 8/9
60000/60000 [==============================] - 7s 111us/step - loss: 0.0157 - acc: 0.9953
Epoch 9/9
60000/60000 [==============================] - 7s 114us/step - loss: 0.0119 - acc: 0.9967


In [12]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 78us/step
test_acc: 0.9816


In [13]:
x = np.array(12)
x

array(12)

In [14]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [15]:
x.ndim

1

In [16]:
x = np.array([[5, 78, 2, 34, 0],[6, 79, 3, 35, 1],[7, 80, 4, 36, 2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [17]:
x.ndim

2

In [18]:
x = np.array([[[5, 78, 2, 34, 0],[6, 79, 3, 35, 1],[7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],[6, 79, 3, 35, 1],[7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],[6, 79, 3, 35, 1],[7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [19]:
x.ndim

3

In [20]:
 print(train_images.ndim)

2


In [21]:
print(train_images.shape)

(60000, 784)


In [22]:
print(train_images.dtype)

float32
